name: Build and deploy Python app to Azure Web App - opentrue-ai

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (İsteğe bağlı) Python setuplamak sadece test için gerekirdi.
      # Deploy için şart değil; webapps-deploy paketi zipleyip gönderecek.
      # Yine de basic doğrulama için pip install çalıştırabiliriz.
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Verify required files exist
        run: |
          test -f app.py || (echo "app.py missing" && exit 1)
          test -f core.py || (echo "core.py missing" && exit 1)
          test -f Procfile || (echo "Procfile missing" && exit 1)
          test -f requirements.txt || (echo "requirements.txt missing" && exit 1)
          test -f rules.txt || (echo "rules.txt missing" && exit 1)
          test -f Keep_Me_Certified_MA_Exam_Prep_Book.pdf || (echo "PDF missing" && exit 1)

      # İstersen burada test amaçlı pip install ile syntax hatası yakalanır
      - name: (Optional) Quick install check
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Azure Web Apps Deploy (Zip Deploy)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: opentrue-ai
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_OPENTRUE_AI }}
          package: . 