name: Deploy to Azure Web App (Folder Package)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: appservice-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # (İsteğe bağlı) Python kurulumuna ihtiyacın yoksa bu adımı silebilirsin
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Prepare deployment folder (minimal)
      run: |
        set -e
        rm -rf deploy
        mkdir -p deploy/cache/artifacts

        # GEREKEN dosyaları AÇIKÇA kopyala
        cp app.py Procfile core.py requirements.txt rules.txt deploy/
        # PDF dosya adını birebir doğru yaz (uzantı dahil!)
        cp "Keep_Me_Certified_MA_Exam_Prep_Book.pdf" deploy/

        # (Varsa) artefact'ları ekle; yoksa sorun yapma
        if compgen -G "artifacts/*" > /dev/null; then
          cp artifacts/* deploy/cache/artifacts/
        else
          echo "No artifacts to copy"
        fi

        # Temizlik: gereksiz büyük klasörleri kesinlikle deploy etme
        rm -rf deploy/__pycache__ || true

    - name: Verify deployment folder
      run: |
        set -e
        echo "=== deploy/ içeriği ==="
        ls -lah deploy
        echo "=== cache/artifacts/ içeriği ==="
        ls -lah deploy/cache/artifacts || true

        # Zorunlu dosyalar kontrolü (yoksa FAIL et)
        for f in app.py Procfile core.py requirements.txt rules.txt "Keep_Me_Certified_MA_Exam_Prep_Book.pdf"; do
          test -f "deploy/$f" || (echo "Missing: deploy/$f" && exit 1)
        done

    - name: Deploy to Azure WebApp (folder)
      uses: azure/webapps-deploy@v2
      with:
        app-name: opentrue-ai
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_OPENTRUE_AI }}
        package: ./deploy          # ZIP yerine klasör gönderiyoruz
